import type { AuthorizedKeysOptions, SshKeyRecord } from "../ssh-keys";

export function buildAuthorizedKeys(
  keys: SshKeyRecord[],
  options: AuthorizedKeysOptions,
): { content: string; uniqueKeyCount: number } {
  const uniqueKeys = [...new Set(keys.map((key) => key.publicKey))];

  let content = `# Auto-generated by satsuki - ${options.generatedAt.toISOString()}\n`;
  content += "# Do not edit manually. Changes will be overwritten.\n\n";

  for (const key of uniqueKeys) {
    content += `${key}\n`;
  }

  return {
    content,
    uniqueKeyCount: uniqueKeys.length,
  };
}
