import { describe, expect, it } from "bun:test";
import { buildAuthorizedKeys } from "./build-authorized-keys";

describe("buildAuthorizedKeys", () => {
  it("deduplicates public keys and preserves header", () => {
    const result = buildAuthorizedKeys(
      [
        { publicKey: "ssh-ed25519 AAA first" },
        { publicKey: "ssh-ed25519 BBB second" },
        { publicKey: "ssh-ed25519 AAA first" },
      ],
      {
        generatedAt: new Date("2026-03-22T00:00:00.000Z"),
      },
    );

    expect(result.uniqueKeyCount).toBe(2);
    expect(result.content).toContain(
      "# Auto-generated by satsuki - 2026-03-22T00:00:00.000Z",
    );
    expect(result.content.match(/^ssh-ed25519/gm)?.length).toBe(2);
  });
});
